// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiURL54dWzo7FmYqSnpiqY8k9O49mH_Q0',
    appId: '1:142573721021:web:0eed2b8e0fafd36f00aed4',
    messagingSenderId: '142573721021',
    projectId: 'efood-2c55f',
    authDomain: 'efood-2c55f.firebaseapp.com',
    storageBucket: 'efood-2c55f.appspot.com',
    measurementId: 'G-01Q34Y2QJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkzO8eg38cBTYowL8TKEr_orD3vQq9f7A',
    appId: '1:142573721021:android:b0c15c528e1ab78200aed4',
    messagingSenderId: '142573721021',
    projectId: 'efood-2c55f',
    storageBucket: 'efood-2c55f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyTNE_a-RbdTmjKtd3-oGLwY3VFIbNXOs',
    appId: '1:142573721021:ios:16f15fd7c18f60ed00aed4',
    messagingSenderId: '142573721021',
    projectId: 'efood-2c55f',
    storageBucket: 'efood-2c55f.appspot.com',
    iosClientId: '142573721021-b4tj1ki50996eqijuf9svic8ca9gcrdm.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.eFood',
  );
}
